/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyProfileIndexRouteImport } from './routes/my-profile/index'
import { Route as PlansCreateRouteImport } from './routes/plans/create'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as PlansProfileIdRouteImport } from './routes/plans/profile/$id'
import { Route as PlansPlanIdRouteImport } from './routes/plans/plan/$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileIndexRoute = MyProfileIndexRouteImport.update({
  id: '/my-profile/',
  path: '/my-profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansCreateRoute = PlansCreateRouteImport.update({
  id: '/plans/create',
  path: '/plans/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansProfileIdRoute = PlansProfileIdRouteImport.update({
  id: '/plans/profile/$id',
  path: '/plans/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/plan/$id',
  path: '/plans/plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/plans/create': typeof PlansCreateRoute
  '/my-profile/': typeof MyProfileIndexRoute
  '/plans/plan/$id': typeof PlansPlanIdRoute
  '/plans/profile/$id': typeof PlansProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/plans/create': typeof PlansCreateRoute
  '/my-profile': typeof MyProfileIndexRoute
  '/plans/plan/$id': typeof PlansPlanIdRoute
  '/plans/profile/$id': typeof PlansProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/plans/create': typeof PlansCreateRoute
  '/my-profile/': typeof MyProfileIndexRoute
  '/plans/plan/$id': typeof PlansPlanIdRoute
  '/plans/profile/$id': typeof PlansProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/plans/create'
    | '/my-profile/'
    | '/plans/plan/$id'
    | '/plans/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/plans/create'
    | '/my-profile'
    | '/plans/plan/$id'
    | '/plans/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/plans/create'
    | '/my-profile/'
    | '/plans/plan/$id'
    | '/plans/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRoute
  SearchRoute: typeof SearchRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  PlansCreateRoute: typeof PlansCreateRoute
  MyProfileIndexRoute: typeof MyProfileIndexRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  PlansProfileIdRoute: typeof PlansProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile/': {
      id: '/my-profile/'
      path: '/my-profile'
      fullPath: '/my-profile/'
      preLoaderRoute: typeof MyProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/create': {
      id: '/plans/create'
      path: '/plans/create'
      fullPath: '/plans/create'
      preLoaderRoute: typeof PlansCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/profile/$id': {
      id: '/plans/profile/$id'
      path: '/plans/profile/$id'
      fullPath: '/plans/profile/$id'
      preLoaderRoute: typeof PlansProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/plan/$id': {
      id: '/plans/plan/$id'
      path: '/plans/plan/$id'
      fullPath: '/plans/plan/$id'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRoute,
  SearchRoute: SearchRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  PlansCreateRoute: PlansCreateRoute,
  MyProfileIndexRoute: MyProfileIndexRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  PlansProfileIdRoute: PlansProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
